### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ZeProgFactory**
Enhanced presentation,
Added session content summary
Added more links (videos, blogs)

### CODE REVIEW

**Comment by ZeProgFactory** [comment]
@jfversluis : I changed `README.md` once again after the PR. Anything I've to do to add the "changed changes"?

**Comment by jfversluis** [comment]
I see you pushed the new changes, right? So that should update the PR automatically. Did you check to see if all your changes are listed under the "Files changed" tab at the top?

**Comment by ZeProgFactory** [comment]
Yeap, it was only an update of the same file ;-)

**Comment by jfversluis** [comment]
Then I think you got it all. Thank you for doing this! Makes it a bit more informative :)

**Pull request merged**
